baseURL = 'https://www.spellenclubtyche.nl/'
languageCode = 'nl'
defaultContentLanguage = 'nederlands'
title = 'Spellenclub Tyche'
theme = 'ananke'

[languages]
[languages.nederlands]
languageName = 'Nederlands'
languageCode = 'nl'
title = "Spellenclub Tyche"
weight = 1
contentDir = "content/nl"
[languages.nederlands.params]
read_more_copy = "Lees meer"

[languages.english]
languageName = 'English'
languageCode = 'en'
title = "Tyche Board Game Club"
weight = 2
contentDir = "content/en"
[languages.english.params]
read_more_copy = "Read more"


[params]
background_color_class = "bg-navy"
cover_dimming_class = "bg-black-60"
custom_css = ["custom.css","special.css"]
site_logo = "images/logo01.svg"
body_classes = "font"
